services:
  mysql_206:
    env_file:
      - .env
    container_name: mysql_206
    hostname: mysql_206
    image: mysql:8
    restart: always
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_206:/var/lib/mysql
    ports:
    #  3307 é a porta do host, que joga p dentro do container
      - 3307:3306
    #  3306 é a porta que o MYSQL usa dentro do container
    environment:
      TZ: America/Sao_Paulo